# Configuration file to set options for VShell
# (note: values passed via arguments will override these values)

# Specify the model to use from GROQ : string
model = "llama3-8b-8192"

# Set the temperature for the model (Groq) : float
temperature = 0.7